apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
        - name: auth-volume
          mountPath: /etc/auth
        - name: cert-crt-volume
          mountPath: /cert/crt/
        - name: cert-key-volume
          mountPath: /cert/key/
        env: 
        - name: REGISTRY_AUTH
          value: htpasswd  
        - name: REGISTRY_AUTH_HTPASSWD_PATH  
          value: /etc/auth/htpasswd  
        - name: REGISTRY_AUTH_HTPASSWD_REALM  
          value: Registry Realm  
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: 'true'
        - name: REGISTRY_LOG_LEVEL
          value: 'warn'
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: '/cert/crt/registry.crt'
        - name: REGISTRY_HTTP_TLS_KEY
          value: '/cert/key/registry.key'
        - name: REGISTRY_HTTP_SECRET
          value: "registry15852"
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/var/lib/registry/docker"
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: auth-volume
        secret:
          secretName: registry-auth
      - name: cert-crt-volume
        configMap:
          name: crt-registry
      - name: cert-key-volume
        configMap:
          name: key-registry
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: registry
spec:
  selector:
    app: docker-registry
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-t
  namespace: registry
spec:
  selector:
    app: docker-registry
  ports:
  - name: http
    port: 8001
    targetPort: 8001
  type: ClusterIP


---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-registry
  namespace: registry
  labels:
    type: local  # Sets PV's type to local
    app: registry
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/registry"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: registry
  name:  registry-pvc # Sets name of PVC
  labels:
    app: registry
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
  volumeName: volume-registry